services:
  bagisto:
    image: webkul/bagisto:latest
    ports:
      - "81:80"
    environment:
      APP_URL: "http://207.180.249.87"
      APP_ENV: production
      APP_DEBUG: "false"
    volumes:
      - ./:/var/www/bagisto
      - bagisto-mysql:/var/lib/mysql
      - bagisto-storage:/var/www/bagisto/storage

volumes:
  bagisto-mysql:
  bagisto-storage:
